[book]
authors = ["auburn"]
language = "en"
multilingual = false
src = "src"
title = "Eralk documentation"

[output.html]
site-url = "/~auburn/eralk/"
additional-css = ["custom.css"]
no-section-label = true
